apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.product.name }}
  namespace: {{ .Values.product.namespace }}
spec:
  replicas: {{ .Values.product.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.product.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.product.name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
