apiVersion: v1
kind: Service
metadata:
  name: { { .Values.product.name } }
  namespace: { { .Values.product.namespace } }
spec:
  selector:
    app: { { .Values.product.name } }
  ports:
    - port: 80
      targetPort: 80
